Define resource ID type
ChainSafe/chainbridge-core pull request #117
Opened 2021-10-08 15:46 UTC by nmlinaric

## Description
- Created typing folder in root - substrate has types defined like that and I think it's the best place to keep them there 
- Define resource ID type and use it where required

## Related Issue Or Context
Addition to https://github.com/ChainSafe/chainbridge-core/pull/116

## How Has This Been Tested? Testing details.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation

## Checklist:
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have ensured that all acceptance criteria (or expected behavior) from issue are met
- [ ] I have updated the documentation locally and in chainbridge-docs.
- [ ] I have added tests to cover my changes.
- [x] I have ensured that all the checks are passing and green, I've signed the CLA bot

2021-10-08 15:46 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ChainSafe/chainbridge-core?pullRequest=117) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ChainSafe/chainbridge-core?pullRequest=117) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ChainSafe/chainbridge-core?pullRequest=117) it.</sub>

2021-10-11 08:32 UTC, mpetrun5 commented
Fix linter. There are some type errors

2021-10-11 10:29 UTC, MakMuftic commented on chains/evm/calls/bridge.go
> +func PrepareExecuteProposalInput(sourceDomainID uint8, depositNonce uint64, resourceID [32]byte, calldata []byte, revertOnFail bool) ([]byte, error) {
Function argument `resourceID` should also be of type `types.ResourceID`

2021-10-11 10:29 UTC, MakMuftic commented on chains/evm/calls/bridge.go
> +func PrepareExecuteProposalInput(sourceDomainID uint8, depositNonce uint64, resourceID [32]byte, calldata []byte, revertOnFail bool) ([]byte, error) {
Function argument `resourceID` should also be of type `types.ResourceID`

2021-10-11 10:30 UTC, MakMuftic commented on chains/evm/calls/bridge.go
> +func PrepareVoteProposalInput(sourceDomainID uint8, resourceID [32]byte, calldata []byte) ([]byte, error) {
Same as previous comment

2021-10-12 06:20 UTC, waymobetta commented on chains/substrate/writer/writer.go
> +func (w *SubstrateWriter) createProposal(sourceChain uint8, depositNonce uint64, resourceId internalTypes.ResourceID, args ...interface{}) (*SubstrateProposal, error) {
Check line `26` of this file (`writer.go`); additional type change needed

```go
type Voter interface {
...
ResolveResourceId(id [32]byte) (string, error)
...
}
```

2021-10-12 06:22 UTC, waymobetta requested changes
Check line `26` of `chains/substrate/writer/writer.go`; additional type change needed

```go
type Voter interface {
...
ResolveResourceId(id [32]byte) (string, error)
...
}
```

2021-10-12 06:40 UTC, waymobetta approved these changes

2021-10-12 07:08 UTC, merged