Add contributing guidelines
ChainSafe/chainbridge-core pull request #211
Opened 2021-12-08 12:30 UTC by mpetrun5

- add contributing section to README
- fix existing gofmt errors
- add gofmt check
- add mocks check

## Related Issue Or Context

Closes: ChainSafe/chainbridge-project-backlog#12

## How Has This Been Tested? Testing details.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Documentation

## Checklist:

- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have ensured that all acceptance criteria (or expected behavior) from issue are met
- [ ] I have updated the documentation locally and in chainbridge-docs.
- [] I have added tests to cover my changes.
- [x] I have ensured that all the checks are passing and green, I've signed the CLA bot

2021-12-08 12:41 UTC, nmlinaric approved these changes

2021-12-13 13:52 UTC, MakMuftic requested changes

2021-12-13 13:52 UTC, MakMuftic commented on README.md
> +please check up with the core devs first on our [Discord Server](https://discord.gg/ykXsJKfhgq) or submit an issue on the repo to ensure those changes are in line with the general
Maybe we should note what are relevant channels on discord for ChainBridge

2021-12-13 13:52 UTC, MakMuftic commented on README.md
> + Also, include the steps required to reproduce the problem if possible. Don't forget to remove sensitive data from your log files and consider posting them as a [gist](https://gist.github.com).
I would refactor the last sentence to be clear not to send sensitive data - as currently it almost sounds as we are instructing contributors to send us sensitive data (private key) in gist.

2021-12-13 15:36 UTC, P1sar approved these changes

2021-12-13 16:07 UTC, MakMuftic approved these changes

2021-12-13 16:54 UTC, merged