Refactor E2E tests to use wait instead of fixed sleep
ChainSafe/chainbridge-core pull request #221
Opened 2021-12-15 09:45 UTC by tcar121293

## Description
Refactor E2E tests to use wait instead of fixed sleep
## Related Issue Or Context

Closes: #175 

## How Has This Been Tested? Testing details.
Run e2e tests locally

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation

## Checklist:

- [ ] I have commented my code, particularly in hard-to-understand areas.
- [x] I have ensured that all acceptance criteria (or expected behavior) from issue are met
- [ ] I have updated the documentation locally and in chainbridge-docs.
- [ ] I have added tests to cover my changes.
- [x] I have ensured that all the checks are passing and green, I've signed the CLA bot

2021-12-15 09:51 UTC, mpetrun5 requested changes

2021-12-15 09:51 UTC, mpetrun5 commented on e2e/evm/test.go
> +func WaitForProposalExecuted(s *IntegrationTestSuite, bridge common.Address) {
Probably can be moved to some utility file and accept client.
Don't think IntegrationTestSuite param is needed.

2021-12-15 10:27 UTC, MakMuftic requested changes

2021-12-15 10:27 UTC, MakMuftic commented on chains/evm/cli/utils/utils.go
>  func UserAmountToWei(amount string, decimal *big.Int) (*big.Int, error) {
Could you also move these functions to some separate file - maybe together with ` WaitForProposalExecuted`, as they don't make any sense inside this file.

2021-12-16 11:14 UTC, mpetrun5 requested changes

2021-12-16 11:14 UTC, mpetrun5 commented on e2e/evm/util.go
> +	fmt.Println("dosassss\nnn")
?

2021-12-16 11:40 UTC, MakMuftic commented
@tcar121293 run mock generation locally, it is failing on CI

2021-12-16 15:50 UTC, MakMuftic requested changes

2021-12-16 15:50 UTC, MakMuftic commented on e2e/evm/test.go
> +var TestTimeout = time.Second * 600
I would move this together with `WaitForProposalExecuted` as it is used there.

2021-12-16 15:50 UTC, MakMuftic commented on e2e/evm/util.go
> +			fmt.Println("nesjedosloooooo\nnn")
clean up

2021-12-16 15:50 UTC, MakMuftic commented on e2e/evm/util.go
> +		panic(err)
I think it would be better to return this error and then decide in setup itself what to do if the error occurs

2021-12-17 11:59 UTC, mpetrun5 approved these changes

2021-12-17 13:05 UTC, MakMuftic approved these changes

2021-12-17 13:05 UTC, merged