Nmlinaric/add prepare flag
ChainSafe/chainbridge-core pull request #232
Opened 2022-01-14 07:50 UTC by nmlinaric

## Description
Add `--prepare` flag for logging calldata

Closes: #178 

## How Has This Been Tested? Testing details.
Unit tests + manual testing

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation

## Checklist:
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have ensured that all acceptance criteria (or expected behavior) from issue are met
- [ ] I have updated the documentation locally and in chainbridge-docs.
- [x] I have added tests to cover my changes.
- [x] I have ensured that all the checks are passing and green, I've signed the CLA bot

2022-01-14 11:54 UTC, mpetrun5 requested changes

2022-01-14 11:54 UTC, mpetrun5 commented on chains/evm/calls/transactor/transact.go
> +	log.Info().Msgf("Command calldata: %+v", data)
Probably we should use some pretty print here and also print out to address

2022-01-14 13:51 UTC, P1sar requested changes

2022-01-14 13:51 UTC, P1sar commented on chains/evm/calls/transactor/transact.go
> +	log.Info().Msgf("Command calldata: %+v", data)
Please take a look at the issue in more time. And think what is the purpose of this task, and HOW printed data will be used

2022-01-14 13:51 UTC, P1sar commented on chains/evm/cli/initialize/initialize.go
>  func InitializeClient(
Please add godoc for this method, make sure that purpose of prepare argument is explicitly described

2022-01-14 13:51 UTC, P1sar commented on chains/evm/calls/transactor/transact.go
> +func NewPrepareTransactor() Transactor {
Add godoc for this function

2022-01-14 13:51 UTC, P1sar commented on chains/evm/calls/transactor/transact.go
> +func (t *prepareTransactor) Transact(to *common.Address, data []byte, opts TransactOptions) (*common.Hash, error) {
add godoc for this function

2022-01-17 10:39 UTC, P1sar commented
This flag should also be documented in README CLI section

2022-01-17 13:34 UTC, P1sar approved these changes

2022-01-18 11:11 UTC, mpetrun5 requested changes

2022-01-18 11:11 UTC, mpetrun5 commented on README.md
> +      --prepare                     Generate calldata for contract calls
Maybe also add that it doesn't require private key and it doesn't send transaction

2022-01-18 11:31 UTC, MakMuftic approved these changes

2022-01-18 14:31 UTC, merged