Update message handler to handle the priority data
ChainSafe/chainbridge-core pull request #244
Opened 2022-01-21 12:24 UTC by tcar121293

Update message handler to handle the priority data
## Description
Update erc20 and erc721 message handlers
Add unit tests

## Related Issue Or Context

Closes: #235 

## How Has This Been Tested? Testing details.
Added unit tests

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation

## Checklist:

- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have ensured that all acceptance criteria (or expected behavior) from issue are met
- [ ] I have updated the documentation locally and in chainbridge-docs.
- [x] I have added tests to cover my changes.
- [x] I have ensured that all the checks are passing and green, I've signed the CLA bot

2022-01-25 10:34 UTC, mpetrun5 requested changes

2022-01-25 10:34 UTC, mpetrun5 commented on chains/evm/voter/message-handler.go
> +		data = append(data, common.LeftPadBytes(priorityLen, 1)...) // length of priority (uint8)
Does data have to contain priority data? Seems irrelevant for submitting on chain.. 
I would probably add https://www.sohamkamani.com/golang/options-pattern/ (`...options`) param to creating new proposal and add all extra options that just the relayer needs.

2022-01-25 10:34 UTC, mpetrun5 commented on chains/evm/voter/message-handler.go
> +		priority, ok := m.Payload[2].([]byte)
Probably move logic for extracting priority to separate function.

2022-01-25 10:34 UTC, mpetrun5 commented on chains/evm/voter/message-handler.go
> +		priority, ok := m.Payload[2].([]byte)
Also, why does priority have to be in payload? If we extract priority in event handler into some message metadata that can contain priority and other data then we don't have to have logic here to check if payload is malformed and also we can just pass it to NewProposal as is.

2022-01-28 11:09 UTC, P1sar requested changes

2022-01-28 11:09 UTC, P1sar commented on chains/evm/voter/message-handler.go
> +
I do not think Go-style suppose to have spaces before return statement

2022-01-28 11:09 UTC, P1sar commented on chains/evm/voter/message-handler.go
> +
same as above

2022-01-31 15:57 UTC, MakMuftic approved these changes
LGTM

2022-01-31 16:29 UTC, nmlinaric approved these changes

2022-02-01 09:12 UTC, P1sar approved these changes

2022-02-01 09:57 UTC, mpetrun5 approved these changes

2022-02-01 09:57 UTC, merged