chore: improve evm listener logging
ChainSafe/chainbridge-core pull request #335
Opened 2023-03-17 13:22 UTC by mpetrun5

Improve evm listener logging and add domainID to all logs and log fetching events as debug.

## Description

## Related Issue Or Context

Closes: #<issue>

## How Has This Been Tested? Testing details.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation

## Checklist:

- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have ensured that all acceptance criteria (or expected behavior) from issue are met
- [ ] I have updated the documentation locally and in chainbridge-docs.
- [ ] I have added tests to cover my changes.
- [ ] I have ensured that all the checks are passing and green, I've signed the CLA bot

2023-03-17 13:25 UTC, nmlinaric approved these changes

2023-03-20 09:55 UTC, MakMuftic requested changes

2023-03-20 09:55 UTC, MakMuftic commented on chains/evm/listener/listener.go
> +					l.log.Error().Err(err).Str("DomainID", string(l.domainID)).Msgf("Unable to handle events")
```suggestion
					l.log.Error().Err(err).Msgf("Unable to handle events")
```

2023-03-20 09:57 UTC, MakMuftic approved these changes

2023-03-20 10:21 UTC, merged